/* corpus/va-arg-trap-1.c */
/* Undefined behavior from a call to va_arg with a type other than
   that of the argument passed (in particular, with a type such as
   "float" that can never be the type of an argument passed through
   "...") does not appear until after the va_list expression is
   evaluated.  PR 38483.  */
/* Origin: Joseph Myers <joseph@codesourcery.com> */

#include <stdarg.h>

extern void exit (int);
extern void abort (void);

va_list ap;
float f;

va_list *
foo (void)
{
  exit ((274877906944));
  return &ap;
}

void
bar (int i, ...)
{
  va_start (ap, i);
  

f = va_arg (*foo (), float) + (42) +((int)((((int)(va_arg (*foo (), float))) >>((int)(f)))))+((long)((((double)(f)) -((double)(f)))))+((long)((((int)(va_arg (*foo (), float))) &((int)(f)))))*((short)((((int)(va_arg (*foo (), float))) &((int)(f)))))-((long)((((int)(f)) ^((int)(va_arg (*foo (), float)))))) + (40) +((int)((((int)(((long)((((double)(f)) -((double)(f))))))) >>((int)((40))))))+((int)((((int)((-43))) >>((int)(va_arg (*foo (), float) + (0x98E080) +((int)((((int)(va_arg (*foo (), float))) >>((int)(f)))))+((long)((((double)(f)) -((double)(f)))))+((long)((((int)(va_arg (*foo (), float))) &((int)(f)))))*((short)((((int)(va_arg (*foo (), float))) &((int)(f))))))))))-((short)((((int)(va_arg (*foo (), float) + (-43) +((int)((((int)(va_arg (*foo (), float))) >>((int)(f))))))) &((int)(va_arg (*foo (), float) + (42))))))+((short)((((int)(va_arg (*foo (), float))) ^((int)(((long)((((int)(va_arg (*foo (), float))) &((int)(f)))))*((short)((((int)(va_arg (*foo (), float))) &((int)(f))))))))))*((short)((((int)(((long)((((double)(f)) -((double)(f))))))) |((int)(((long)((((int)(f)) ^((int)(va_arg (*foo (), float))))))))))) + (40) -((long)((((int)(va_arg (*foo (), float) + (-43) +((int)((((int)(va_arg (*foo (), float))) >>((int)(f)))))+((long)((((double)(f)) -((double)(f)))))+((long)((((int)(va_arg (*foo (), float))) &((int)(f)))))*((short)((((int)(va_arg (*foo (), float))) &((int)(f)))))-((long)((((int)(f)) ^((int)(va_arg (*foo (), float)))))) + (-43) +((int)((((int)(((long)((((double)(f)) -((double)(f))))))) >>((int)((-43))))))+((int)((((int)((-43))) >>((int)(va_arg (*foo (), float) + (-43) +((int)((((int)(va_arg (*foo (), float))) >>((int)(f)))))+((long)((((double)(f)) -((double)(f)))))+((long)((((int)(va_arg (*foo (), float))) &((int)(f)))))*((short)((((int)(va_arg (*foo (), float))) &((int)(f))))))))))-((short)((((int)(va_arg (*foo (), float) + (-43) +((int)((((int)(va_arg (*foo (), float))) >>((int)(f))))))) &((int)(va_arg (*foo (), float) + (-43))))))+((short)((((int)(va_arg (*foo (), float))) ^((int)(((long)((((int)(va_arg (*foo (), float))) &((int)(f)))))*((short)((((int)(va_arg (*foo (), float))) &((int)(f))))))))))*((short)((((int)(((long)((((double)(f)) -((double)(f))))))) |((int)(((long)((((int)(f)) ^((int)(va_arg (*foo (), float))))))))))))) |((int)(va_arg (*foo (), float) + (40) +((int)((((int)(va_arg (*foo (), float))) >>((int)(f)))))+((long)((((double)(f)) -((double)(f)))))+((long)((((int)(va_arg (*foo (), float))) &((int)(f)))))*((short)((((int)(va_arg (*foo (), float))) &((int)(f)))))-((long)((((int)(f)) ^((int)(va_arg (*foo (), float)))))) + (0x5F8) +((int)((((int)(((long)((((double)(f)) -((double)(f))))))) >>((int)((0xBF)))))))))));
f = va_arg (*foo (), float) + (0x77CB0D) +((int)((((int)(va_arg (*foo (), float))) >>((int)(f)))))+((long)((((double)(f)) -((double)(f)))))+((long)((((int)(va_arg (*foo (), float))) &((int)(f)))))*((short)((((int)(va_arg (*foo (), float))) &((int)(f)))))-((long)((((int)(f)) ^((int)(va_arg (*foo (), float)))))) + (0xAD9C8F) +((int)((((int)(((long)((((double)(f)) -((double)(f))))))) >>((int)((106))))))+((int)((((int)((-43))) >>((int)(va_arg (*foo (), float) + (-43) +((int)((((int)(va_arg (*foo (), float))) >>((int)(f)))))+((long)((((double)(f)) -((double)(f)))))+((long)((((int)(va_arg (*foo (), float))) &((int)(f)))))*((short)((((int)(va_arg (*foo (), float))) &((int)(f))))))))))-((short)((((int)(va_arg (*foo (), float) + (42) +((int)((((int)(va_arg (*foo (), float))) >>((int)(f))))))) &((int)(va_arg (*foo (), float) + (0xDD))))))+((short)((((int)(va_arg (*foo (), float))) ^((int)(((long)((((int)(va_arg (*foo (), float))) &((int)(f)))))*((short)((((int)(va_arg (*foo (), float))) &((int)(f))))))))))*((short)((((int)(((long)((((double)(f)) -((double)(f))))))) |((int)(((long)((((int)(f)) ^((int)(va_arg (*foo (), float))))))))))) + (42) -((long)((((int)(va_arg (*foo (), float) + (0x35E1) +((int)((((int)(va_arg (*foo (), float))) >>((int)(f)))))+((long)((((double)(f)) -((double)(f)))))+((long)((((int)(va_arg (*foo (), float))) &((int)(f)))))*((short)((((int)(va_arg (*foo (), float))) &((int)(f)))))-((long)((((int)(f)) ^((int)(va_arg (*foo (), float)))))) + (106) +((int)((((int)(((long)((((double)(f)) -((double)(f))))))) >>((int)((40))))))+((int)((((int)((0xC917))) >>((int)(va_arg (*foo (), float) + (0x550832) +((int)((((int)(va_arg (*foo (), float))) >>((int)(f)))))+((long)((((double)(f)) -((double)(f)))))+((long)((((int)(va_arg (*foo (), float))) &((int)(f)))))*((short)((((int)(va_arg (*foo (), float))) &((int)(f))))))))))-((short)((((int)(va_arg (*foo (), float) + (42) +((int)((((int)(va_arg (*foo (), float))) >>((int)(f))))))) &((int)(va_arg (*foo (), float) + (0x7E928))))))+((short)((((int)(va_arg (*foo (), float))) ^((int)(((long)((((int)(va_arg (*foo (), float))) &((int)(f)))))*((short)((((int)(va_arg (*foo (), float))) &((int)(f))))))))))*((short)((((int)(((long)((((double)(f)) -((double)(f))))))) |((int)(((long)((((int)(f)) ^((int)(va_arg (*foo (), float))))))))))))) |((int)(va_arg (*foo (), float) + (-43) +((int)((((int)(va_arg (*foo (), float))) >>((int)(f)))))+((long)((((double)(f)) -((double)(f)))))+((long)((((int)(va_arg (*foo (), float))) &((int)(f)))))*((short)((((int)(va_arg (*foo (), float))) &((int)(f)))))-((long)((((int)(f)) ^((int)(va_arg (*foo (), float)))))) + (0x7E) +((int)((((int)(((long)((((double)(f)) -((double)(f))))))) >>((int)((42)))))))))));
;

f = va_arg (*foo (), float) + (34) +((int)((((int)(va_arg (*foo (), float))) >>((int)(f)))))+((long)((((double)(f)) -((double)(f)))))+((long)((((int)(va_arg (*foo (), float))) &((int)(f)))))*((short)((((int)(va_arg (*foo (), float))) &((int)(f)))))-((long)((((int)(f)) ^((int)(va_arg (*foo (), float)))))) + (0xF9C1) +((long)((((int)(f)) &((int)(va_arg (*foo (), float))))))+((short)((((int)(va_arg (*foo (), float) + (170))) %((int)(((int)((((int)(va_arg (*foo (), float))) >>((int)(f))))))))))*((short)((((int)(((long)((((int)(f)) ^((int)(va_arg (*foo (), float)))))))) ^((int)(va_arg (*foo (), float) + (10) +((int)((((int)(va_arg (*foo (), float))) >>((int)(f)))))+((long)((((double)(f)) -((double)(f)))))+((long)((((int)(va_arg (*foo (), float))) &((int)(f)))))*((short)((((int)(va_arg (*foo (), float))) &((int)(f)))))-((long)((((int)(f)) ^((int)(va_arg (*foo (), float)))))))))))*((int)((((int)(va_arg (*foo (), float) + (10) +((int)((((int)(va_arg (*foo (), float))) >>((int)(f)))))+((long)((((double)(f)) -((double)(f)))))+((long)((((int)(va_arg (*foo (), float))) &((int)(f)))))*((short)((((int)(va_arg (*foo (), float))) &((int)(f)))))-((long)((((int)(f)) ^((int)(va_arg (*foo (), float)))))))) <<((int)(va_arg (*foo (), float) + (-43) +((int)((((int)(va_arg (*foo (), float))) >>((int)(f)))))+((long)((((double)(f)) -((double)(f))))))))))+((short)((((int)(f)) ^((int)(va_arg (*foo (), float) + (72) +((int)((((int)(va_arg (*foo (), float))) >>((int)(f)))))))))) + (0xA3FD3E) *((long)((((int)(va_arg (*foo (), float) + (58) +((int)((((int)(va_arg (*foo (), float))) >>((int)(f)))))+((long)((((double)(f)) -((double)(f)))))+((long)((((int)(va_arg (*foo (), float))) &((int)(f)))))*((short)((((int)(va_arg (*foo (), float))) &((int)(f))))))) %((int)(((short)((((int)(f)) ^((int)(va_arg (*foo (), float) + (0x610F) +((int)((((int)(va_arg (*foo (), float))) >>((int)(f)))))))))))))))+((short)((((int)(((short)((((int)(f)) ^((int)(va_arg (*foo (), float) + (-43) +((int)((((int)(va_arg (*foo (), float))) >>((int)(f)))))))))))) &((int)(((int)((((int)(va_arg (*foo (), float))) >>((int)(f))))))))))-((int)((((int)(va_arg (*foo (), float) + (42) +((int)((((int)(va_arg (*foo (), float))) >>((int)(f))))))) %((int)(f)))))*((short)((((int)(f)) |((int)(va_arg (*foo (), float) + (42) +((int)((((int)(va_arg (*foo (), float))) >>((int)(f)))))+((long)((((double)(f)) -((double)(f)))))+((long)((((int)(va_arg (*foo (), float))) &((int)(f)))))*((short)((((int)(va_arg (*foo (), float))) &((int)(f)))))-((long)((((int)(f)) ^((int)(va_arg (*foo (), float)))))) + (42) +((long)((((int)(f)) &((int)(va_arg (*foo (), float)))))))))));
f = va_arg (*foo (), float) + (0x521) +((int)((((int)(va_arg (*foo (), float))) >>((int)(f)))))+((long)((((double)(f)) -((double)(f)))))+((long)((((int)(va_arg (*foo (), float))) &((int)(f)))))*((short)((((int)(va_arg (*foo (), float))) &((int)(f)))))-((long)((((int)(f)) ^((int)(va_arg (*foo (), float)))))) + (-43) +((long)((((int)(f)) &((int)(va_arg (*foo (), float))))))+((short)((((int)(va_arg (*foo (), float) + (-43))) %((int)(((int)((((int)(va_arg (*foo (), float))) >>((int)(f))))))))))*((short)((((int)(((long)((((int)(f)) ^((int)(va_arg (*foo (), float)))))))) ^((int)(va_arg (*foo (), float) + (34) +((int)((((int)(va_arg (*foo (), float))) >>((int)(f)))))+((long)((((double)(f)) -((double)(f)))))+((long)((((int)(va_arg (*foo (), float))) &((int)(f)))))*((short)((((int)(va_arg (*foo (), float))) &((int)(f)))))-((long)((((int)(f)) ^((int)(va_arg (*foo (), float)))))))))))*((int)((((int)(va_arg (*foo (), float) + (-43) +((int)((((int)(va_arg (*foo (), float))) >>((int)(f)))))+((long)((((double)(f)) -((double)(f)))))+((long)((((int)(va_arg (*foo (), float))) &((int)(f)))))*((short)((((int)(va_arg (*foo (), float))) &((int)(f)))))-((long)((((int)(f)) ^((int)(va_arg (*foo (), float)))))))) <<((int)(va_arg (*foo (), float) + (43) +((int)((((int)(va_arg (*foo (), float))) >>((int)(f)))))+((long)((((double)(f)) -((double)(f))))))))))+((short)((((int)(f)) ^((int)(va_arg (*foo (), float) + (-43) +((int)((((int)(va_arg (*foo (), float))) >>((int)(f)))))))))) + (42) *((long)((((int)(va_arg (*foo (), float) + (0x05) +((int)((((int)(va_arg (*foo (), float))) >>((int)(f)))))+((long)((((double)(f)) -((double)(f)))))+((long)((((int)(va_arg (*foo (), float))) &((int)(f)))))*((short)((((int)(va_arg (*foo (), float))) &((int)(f))))))) %((int)(((short)((((int)(f)) ^((int)(va_arg (*foo (), float) + (58) +((int)((((int)(va_arg (*foo (), float))) >>((int)(f)))))))))))))))+((short)((((int)(((short)((((int)(f)) ^((int)(va_arg (*foo (), float) + (42) +((int)((((int)(va_arg (*foo (), float))) >>((int)(f)))))))))))) &((int)(((int)((((int)(va_arg (*foo (), float))) >>((int)(f))))))))))-((int)((((int)(va_arg (*foo (), float) + (42) +((int)((((int)(va_arg (*foo (), float))) >>((int)(f))))))) %((int)(f)))))*((short)((((int)(f)) |((int)(va_arg (*foo (), float) + (0x60) +((int)((((int)(va_arg (*foo (), float))) >>((int)(f)))))+((long)((((double)(f)) -((double)(f)))))+((long)((((int)(va_arg (*foo (), float))) &((int)(f)))))*((short)((((int)(va_arg (*foo (), float))) &((int)(f)))))-((long)((((int)(f)) ^((int)(va_arg (*foo (), float)))))) + (43) +((long)((((int)(f)) &((int)(va_arg (*foo (), float)))))))))));
;
;
  va_end (ap);
}

int
main (void)
{
  bar ((0x0255), (268435456));
  abort ();
}
/* ProgramSourceLLVM */
