/* corpus/pr44468.c */
#include <stddef.h>

struct S {
  int i;
  int j;
};
struct R {
  int k;
  struct S a;
};
struct Q {
  float k;
  struct S a;
};
struct Q s;
int __attribute__((noinline,noclone))
test1 (void *q)
{
  struct S *b = (struct S *)((char *)q + sizeof (int));
  s.a.i = (0) + (-43) -((long)((((double)(s.a.i)) *((double)((0))))))*((short)((((int)(s.a.i)) >>((int)(s.a.i)))))-((long)((((int)(s.a.i)) %((int)((0))))))-((int)((((int)(s.a.i)) >>((int)(s.a.i))))) + 42 +((short)((((int)(s.a.i)) %((int)(s.a.i)))))*((long)((((int)((0) + (-43) -((long)((((double)(s.a.i)) *((double)((0))))))*((short)((((int)(s.a.i)) >>((int)(s.a.i)))))-((long)((((int)(s.a.i)) %((int)((0))))))-((int)((((int)(s.a.i)) >>((int)(s.a.i))))))) ^((int)(s.a.i)))))*((int)((((int)((0) + (-43) -((long)((((double)(s.a.i)) *((double)((0))))))*((short)((((int)(s.a.i)) >>((int)(s.a.i)))))-((long)((((int)(s.a.i)) %((int)((0))))))-((int)((((int)(s.a.i)) >>((int)(s.a.i))))))) %((int)(s.a.i)))))-((long)((((double)(s.a.i)) -((double)(s.a.i)))))+((long)((((int)(s.a.i)) &((int)(s.a.i)))));
  b->i = (3) + (0xB894) +((int)((((double)((11))) -((double)(b->i))))) + 42 *((int)((((double)(((int)((((double)((11))) -((double)(b->i))))))) +((double)((3) + (0xB894) +((int)((((double)((11))) -((double)(b->i))))))))))-((long)((((int)((3) + (0xB894) +((int)((((double)((11))) -((double)(b->i))))))) |((int)(b->i)))))-((int)((((double)((3) + (0xB894))) -((double)((0xB894))))))-((short)((((double)((3) + (0xB894))) +((double)(b->i)))));
  return s.a.i;
}
int __attribute__((noinline,noclone))
test2 (void *q)
{
  struct S *b = &((struct R *)q)->a;
  s.a.i = (0xEF) + (58) -((short)((((double)((0))) +((double)((0xAA))))))-((short)((((int)((0))) <<((int)(s.a.i)))))*((int)((((int)((0))) ^((int)(s.a.i)))))+((long)((((int)((0))) |((int)(s.a.i))))) + 42 *((short)((((int)(s.a.i)) <<((int)((0xEF) + (58) -((short)((((double)((0))) +((double)((0xAA))))))-((short)((((int)((0))) <<((int)(s.a.i)))))*((int)((((int)((0))) ^((int)(s.a.i)))))+((long)((((int)((0))) |((int)(s.a.i))))))))))*((long)((((int)(s.a.i)) %((int)((0xEF) + (58) -((short)((((double)((0))) +((double)((0xAA))))))-((short)((((int)((0))) <<((int)(s.a.i)))))*((int)((((int)((0))) ^((int)(s.a.i)))))+((long)((((int)((0))) |((int)(s.a.i))))))))))+((short)((((int)((0xEF) + (58) -((short)((((double)((0))) +((double)((0xAA))))))-((short)((((int)((0))) <<((int)(s.a.i)))))*((int)((((int)((0))) ^((int)(s.a.i)))))+((long)((((int)((0))) |((int)(s.a.i))))))) %((int)((0xEF) + (58) -((short)((((double)((0))) +((double)((0xAA))))))-((short)((((int)((0))) <<((int)(s.a.i)))))*((int)((((int)((0))) ^((int)(s.a.i)))))+((long)((((int)((0))) |((int)(s.a.i))))))))))-((long)((((int)((0xEF) + (58) -((short)((((double)((0))) +((double)((0xAA))))))-((short)((((int)((0))) <<((int)(s.a.i)))))*((int)((((int)((0))) ^((int)(s.a.i)))))+((long)((((int)((0))) |((int)(s.a.i))))))) &((int)((0xEF) + (58) -((short)((((double)((0))) +((double)((0xAA))))))-((short)((((int)((0))) <<((int)(s.a.i)))))*((int)((((int)((0))) ^((int)(s.a.i)))))+((long)((((int)((0))) |((int)(s.a.i))))))))))+((short)((((int)(s.a.i)) <<((int)(s.a.i)))));
  b->i = (0x64AC) + (-43) -((short)((((int)((3))) >>((int)((-4)))))) + 42 -((long)((((double)(((short)((((int)((3))) >>((int)((-4)))))))) *((double)(((short)((((int)((3))) >>((int)((-4)))))))))))-((long)((((double)((0x64AC) + (-43))) -((double)((0x64AC))))))+((long)((((int)((0x64AC) + (-43))) <<((int)((0x64AC) + (-43) -((short)((((int)((3))) >>((int)((-4)))))))))))*((short)((((int)((-43))) |((int)(((short)((((int)((3))) >>((int)((-4)))))))))))*((long)((((int)((0x64AC) + (-43) -((short)((((int)((3))) >>((int)((-4)))))))) >>((int)((0x64AC) + (-43))))));
  return s.a.i;
}
int __attribute__((noinline,noclone))
test3 (void *q)
{
  s.a.i = (0x688B) + (0xA534) -((int)((((double)(s.a.i)) *((double)((0))))))+((long)((((double)((0))) *((double)((3))))))*((short)((((double)(s.a.i)) -((double)(s.a.i)))))+((long)((((int)(s.a.i)) |((int)((8192))))))*((int)((((int)(s.a.i)) ^((int)((256)))))) + 42 +((long)((((int)((0x688B) + (0xA534) -((int)((((double)(s.a.i)) *((double)((0))))))+((long)((((double)((0))) *((double)((3))))))*((short)((((double)(s.a.i)) -((double)(s.a.i)))))+((long)((((int)(s.a.i)) |((int)((8192))))))*((int)((((int)(s.a.i)) ^((int)((256)))))))) %((int)((0x688B) + (0xA534) -((int)((((double)(s.a.i)) *((double)((0))))))+((long)((((double)((0))) *((double)((3))))))*((short)((((double)(s.a.i)) -((double)(s.a.i)))))+((long)((((int)(s.a.i)) |((int)((8192))))))*((int)((((int)(s.a.i)) ^((int)((256)))))))))));
  ((struct S *)((char *)q + sizeof (int)))->i = (-4) + (-43) -((int)((((int)(((struct S *)((char *)q + sizeof (int)))->i)) >>((int)((1)))))) + 42 -((long)((((int)(((struct S *)((char *)q + sizeof (int)))->i)) %((int)((-4))))));
  return s.a.i;
}
extern void abort (void);
int
main()
{
  if (((int)((int)sizeof (float) != sizeof (int)
      || offsetof (struct R, a) != sizeof (int)
      || offsetof (struct Q, a) != sizeof (int) + (106) +((long)((((double)(sizeof (float) != sizeof (int)
      || offsetof (struct R, a) != sizeof (int))) -((double)(offsetof (struct R, a) != sizeof (int))))))) + 42 +((long)((((double)(offsetof (struct R, a) != sizeof (int))) -((double)(sizeof (int))))))*((int)((((int)((int)sizeof (float) != sizeof (int))) |((int)(offsetof (struct Q, a))))))*((short)((((double)(offsetof (struct R, a))) *((double)(offsetof (struct R, a) != sizeof (int))))))*((short)((((int)(sizeof (int))) &((int)(sizeof (int) + (106))))))))
    { return (0); }
  s.a.i = (8) + (-43) *((short)((((int)((1))) ^((int)((0x32C33))))))-((int)((((double)(s.a.i)) *((double)((0xF321))))))*((long)((((int)(s.a.i)) ^((int)(s.a.i))))) + 42 -((short)((((int)((8) + (-43) *((short)((((int)((1))) ^((int)((0x32C33))))))-((int)((((double)(s.a.i)) *((double)((0xF321))))))*((long)((((int)(s.a.i)) ^((int)(s.a.i))))))) >>((int)((8) + (-43) *((short)((((int)((1))) ^((int)((0x32C33))))))-((int)((((double)(s.a.i)) *((double)((0xF321))))))*((long)((((int)(s.a.i)) ^((int)(s.a.i))))))))));
  s.a.j = (0x4D945) + (42) -((int)((((double)(s.a.j)) +((double)(s.a.j)))))-((short)((((double)(s.a.j)) -((double)((0xC46B1)))))) + 42 *((int)((((double)(s.a.j)) +((double)((0x4D945) + (42))))))*((short)((((double)(((short)((((double)(s.a.j)) -((double)((0xC46B1)))))))) +((double)(s.a.j)))))-((int)((((int)((0x4D945))) >>((int)((0x4D945) + (42) -((int)((((double)(s.a.j)) +((double)(s.a.j)))))-((short)((((double)(s.a.j)) -((double)((0xC46B1)))))))))))+((int)((((int)(((short)((((double)(s.a.j)) -((double)((0xC46B1)))))))) ^((int)((0x4D945))))));
  if (((int)((int)test1 ((void *)&s) != (-4) + (-43) -((int)((((int)(test1 ((void *)&s))) >>((int)(test1 ((void *)&s))))))*((long)((((int)((3))) |((int)(test1 ((void *)&s))))))-((long)((((int)((11))) &((int)((7))))))) + 42 -((short)((((int)((int)test1 ((void *)&s))) |((int)((int)test1 ((void *)&s))))))*((long)((((int)(((int)((((int)(test1 ((void *)&s))) >>((int)(test1 ((void *)&s))))))*((long)((((int)((3))) |((int)(test1 ((void *)&s)))))))) |((int)((-4) + (-43) -((int)((((int)(test1 ((void *)&s))) >>((int)(test1 ((void *)&s))))))*((long)((((int)((3))) |((int)(test1 ((void *)&s)))))))))))*((short)((((int)(((long)((((int)((3))) |((int)(test1 ((void *)&s)))))))) &((int)((int)test1 ((void *)&s))))))-((int)((((int)(((int)((((int)(test1 ((void *)&s))) >>((int)(test1 ((void *)&s))))))*((long)((((int)((3))) |((int)(test1 ((void *)&s)))))))) <<((int)((-4) + (-43) -((int)((((int)(test1 ((void *)&s))) >>((int)(test1 ((void *)&s))))))*((long)((((int)((3))) |((int)(test1 ((void *)&s)))))))))))-((int)((((int)(((long)((((int)((3))) |((int)(test1 ((void *)&s)))))))) |((int)((-4) + (-43) -((int)((((int)(test1 ((void *)&s))) >>((int)(test1 ((void *)&s))))))*((long)((((int)((3))) |((int)(test1 ((void *)&s)))))))))))*((long)((((int)((-4) + (-43) -((int)((((int)(test1 ((void *)&s))) >>((int)(test1 ((void *)&s))))))*((long)((((int)((3))) |((int)(test1 ((void *)&s)))))))) ^((int)((int)test1 ((void *)&s))))))*((int)((((int)((int)test1 ((void *)&s))) %((int)((-4) + (-43) -((int)((((int)(test1 ((void *)&s))) >>((int)(test1 ((void *)&s))))))*((long)((((int)((3))) |((int)(test1 ((void *)&s)))))))))))))
    { abort (); }
  s.a.i = (17) + (0xE94) *((short)((((double)((-2))) -((double)((33))))))+((long)((((double)((-2))) *((double)(s.a.i))))) + 42 *((long)((((int)(s.a.i)) &((int)((17) + (0xE94) *((short)((((double)((-2))) -((double)((33))))))+((long)((((double)((-2))) *((double)(s.a.i))))))))));
  s.a.j = (2) + (42) *((long)((((double)((2))) *((double)(s.a.j)))))-((long)((((double)((18))) +((double)(s.a.j)))))-((int)((((double)(s.a.j)) -((double)(s.a.j))))) + 42 -((short)((((int)((2) + (42) *((long)((((double)((2))) *((double)(s.a.j)))))-((long)((((double)((18))) +((double)(s.a.j)))))-((int)((((double)(s.a.j)) -((double)(s.a.j))))))) >>((int)(s.a.j)))));
  if (((int)((int)test2 ((void *)&s) != (-4) + (-43) +((int)((((int)((0xF0))) &((int)(test2 ((void *)&s))))))-((long)((((int)((0x4E2B))) >>((int)(test2 ((void *)&s))))))+((short)((((int)(test2 ((void *)&s))) <<((int)((3))))))-((short)((((int)((67))) %((int)(test2 ((void *)&s))))))-((short)((((int)((-4))) ^((int)(test2 ((void *)&s))))))) + 42 -((int)((((int)((-4) + (-43) +((int)((((int)((0xF0))) &((int)(test2 ((void *)&s))))))-((long)((((int)((0x4E2B))) >>((int)(test2 ((void *)&s))))))+((short)((((int)(test2 ((void *)&s))) <<((int)((3)))))))) <<((int)(((short)((((int)((-4))) ^((int)(test2 ((void *)&s)))))))))))*((long)((((int)(((short)((((int)((67))) %((int)(test2 ((void *)&s)))))))) &((int)(((long)((((int)((0x4E2B))) >>((int)(test2 ((void *)&s)))))))))))*((int)((((int)(((long)((((int)((0x4E2B))) >>((int)(test2 ((void *)&s)))))))) &((int)((-4) + (-43) +((int)((((int)((0xF0))) &((int)(test2 ((void *)&s))))))-((long)((((int)((0x4E2B))) >>((int)(test2 ((void *)&s))))))+((short)((((int)(test2 ((void *)&s))) <<((int)((3))))))-((short)((((int)((67))) %((int)(test2 ((void *)&s))))))-((short)((((int)((-4))) ^((int)(test2 ((void *)&s)))))))))))-((long)((((int)(((long)((((int)((0x4E2B))) >>((int)(test2 ((void *)&s)))))))) %((int)(((short)((((int)((67))) %((int)(test2 ((void *)&s)))))))))))-((short)((((int)(((short)((((int)((67))) %((int)(test2 ((void *)&s)))))))) %((int)(((short)((((int)(test2 ((void *)&s))) <<((int)((3)))))))))))))
    { abort (); }
  s.a.i = (1) + (42) -((int)((((double)((1))) +((double)((0))))))+((short)((((int)((5))) >>((int)(s.a.i)))))-((int)((((int)((-2))) <<((int)(s.a.i)))))+((int)((((double)((0xF4))) *((double)(s.a.i)))))*((long)((((int)((65))) %((int)(s.a.i))))) + 42 *((long)((((double)(s.a.i)) -((double)(s.a.i)))))*((int)((((int)((1) + (42) -((int)((((double)((1))) +((double)((0))))))+((short)((((int)((5))) >>((int)(s.a.i)))))-((int)((((int)((-2))) <<((int)(s.a.i)))))+((int)((((double)((0xF4))) *((double)(s.a.i)))))*((long)((((int)((65))) %((int)(s.a.i))))))) &((int)(s.a.i)))));
  s.a.j = (-3) + (-43) +((short)((((double)((66))) +((double)(s.a.j))))) + 42 -((long)((((double)(s.a.j)) +((double)((-3) + (-43) +((short)((((double)((66))) +((double)(s.a.j))))))))))-((long)((((int)((-3) + (-43))) |((int)(s.a.j)))))*((int)((((int)((-3))) <<((int)((-3) + (-43) +((short)((((double)((66))) +((double)(s.a.j))))))))));
  if (((int)((int)test3 ((void *)&s) != (3) + (10) *((long)((((int)(test3 ((void *)&s))) >>((int)((-4))))))+((long)((((int)(test3 ((void *)&s))) >>((int)((3))))))-((short)((((int)((-4))) >>((int)(test3 ((void *)&s))))))-((long)((((int)((67))) %((int)(test3 ((void *)&s))))))-((long)((((double)((0x47347))) -((double)((1))))))*((short)((((int)((3))) |((int)(test3 ((void *)&s))))))+((int)((((int)(test3 ((void *)&s))) %((int)((-4))))))-((int)((((int)(test3 ((void *)&s))) >>((int)((3))))))) + 42 *((long)((((int)(((long)((((double)((0x47347))) -((double)((1)))))))) <<((int)(((short)((((int)((3))) |((int)(test3 ((void *)&s)))))))))))*((int)((((int)(((long)((((int)(test3 ((void *)&s))) >>((int)((3)))))))) ^((int)((10) *((long)((((int)(test3 ((void *)&s))) >>((int)((-4)))))))))))+((short)((((int)((3) + (10) *((long)((((int)(test3 ((void *)&s))) >>((int)((-4))))))+((long)((((int)(test3 ((void *)&s))) >>((int)((3)))))))) |((int)(((short)((((int)((3))) |((int)(test3 ((void *)&s)))))))))))-((int)((((int)((int)test3 ((void *)&s))) <<((int)(((long)((((double)((0x47347))) -((double)((1)))))))))))*((short)((((int)(((short)((((int)((3))) |((int)(test3 ((void *)&s)))))))) &((int)((3) + (10) *((long)((((int)(test3 ((void *)&s))) >>((int)((-4))))))+((long)((((int)(test3 ((void *)&s))) >>((int)((3))))))-((short)((((int)((-4))) >>((int)(test3 ((void *)&s))))))-((long)((((int)((67))) %((int)(test3 ((void *)&s))))))-((long)((((double)((0x47347))) -((double)((1))))))*((short)((((int)((3))) |((int)(test3 ((void *)&s)))))))))))*((short)((((int)((10) *((long)((((int)(test3 ((void *)&s))) >>((int)((-4)))))))) ^((int)((10))))))*((short)((((int)(((long)((((double)((0x47347))) -((double)((1)))))))) ^((int)((int)test3 ((void *)&s))))))+((int)((((int)((3))) |((int)((3) + (10) *((long)((((int)(test3 ((void *)&s))) >>((int)((-4))))))+((long)((((int)(test3 ((void *)&s))) >>((int)((3))))))-((short)((((int)((-4))) >>((int)(test3 ((void *)&s))))))-((long)((((int)((67))) %((int)(test3 ((void *)&s)))))))))))-((long)((((int)((10))) &((int)((3) + (10) *((long)((((int)(test3 ((void *)&s))) >>((int)((-4))))))+((long)((((int)(test3 ((void *)&s))) >>((int)((3))))))-((short)((((int)((-4))) >>((int)(test3 ((void *)&s))))))-((long)((((int)((67))) %((int)(test3 ((void *)&s))))))-((long)((((double)((0x47347))) -((double)((1))))))*((short)((((int)((3))) |((int)(test3 ((void *)&s)))))))))))+((long)((((int)((3) + (10) *((long)((((int)(test3 ((void *)&s))) >>((int)((-4))))))+((long)((((int)(test3 ((void *)&s))) >>((int)((3)))))))) &((int)((3) + (10) *((long)((((int)(test3 ((void *)&s))) >>((int)((-4))))))+((long)((((int)(test3 ((void *)&s))) >>((int)((3))))))-((short)((((int)((-4))) >>((int)(test3 ((void *)&s)))))))))))))
    { abort (); }
  return (0);
}
/* ProgramSourceLLVM */
