/* corpus/pr44468.c */
#include <stddef.h>

struct S {
  int i;
  int j;
};
struct R {
  int k;
  struct S a;
};
struct Q {
  float k;
  struct S a;
};
struct Q s;
int __attribute__((noinline,noclone))
test1 (void *q)
{
  struct S *b = (struct S *)((char *)q + sizeof (int));
  s.a.i = (33554432) + (-43) *((int)((((double)((128))) +((double)(s.a.i)))))-((int)((((int)((-1))) &((int)(s.a.i)))))*((short)((((double)(s.a.i)) +((double)(s.a.i)))))*((long)((((double)((-1))) +((double)((0xFCCC)))))) + (43) -((long)((((int)((0) + (0x4543) *((int)((((double)((-1))) +((double)(s.a.i)))))-((int)((((int)((0))) &((int)(s.a.i)))))*((short)((((double)(s.a.i)) +((double)(s.a.i)))))*((long)((((double)((2))) +((double)((0)))))))) &((int)((-1) + (62) *((int)((((double)((0))) +((double)(s.a.i)))))-((int)((((int)((0))) &((int)(s.a.i)))))*((short)((((double)(s.a.i)) +((double)(s.a.i)))))*((long)((((double)((0x42E8C))) +((double)((1)))))))))))*((short)((((int)((0) + (106) *((int)((((double)((32))) +((double)(s.a.i)))))-((int)((((int)((0))) &((int)(s.a.i)))))*((short)((((double)(s.a.i)) +((double)(s.a.i)))))*((long)((((double)((0x244D))) +((double)((0)))))))) >>((int)(s.a.i)))))+((long)((((int)((-1) + (-43) *((int)((((double)((-1))) +((double)(s.a.i)))))-((int)((((int)((0))) &((int)(s.a.i)))))*((short)((((double)(s.a.i)) +((double)(s.a.i)))))*((long)((((double)((0))) +((double)((2)))))))) |((int)((0) + (0x393E78) *((int)((((double)((8))) +((double)(s.a.i)))))-((int)((((int)((-1))) &((int)(s.a.i)))))*((short)((((double)(s.a.i)) +((double)(s.a.i)))))*((long)((((double)((5))) +((double)((0x01)))))))))))+((int)((((int)((262144) + (0x20A) *((int)((((double)((0xD17))) +((double)(s.a.i)))))-((int)((((int)((0))) &((int)(s.a.i)))))*((short)((((double)(s.a.i)) +((double)(s.a.i)))))*((long)((((double)((0x8D6F8))) +((double)((0x8B2C)))))))) <<((int)(s.a.i)))))+((long)((((int)((16) + (42) *((int)((((double)((140737488355328))) +((double)(s.a.i)))))-((int)((((int)((8589934592))) &((int)(s.a.i)))))*((short)((((double)(s.a.i)) +((double)(s.a.i)))))*((long)((((double)((0x5AC))) +((double)((0x323)))))))) <<((int)(s.a.i)))));
  b->i = (0x26) + (0xA0315) *((long)((((int)((-4))) >>((int)((-4))))))+((long)((((double)((3))) *((double)(b->i)))))-((int)((((double)(b->i)) -((double)((67))))))+((long)((((double)(b->i)) *((double)((3)))))) + (34) -((short)((((double)(b->i)) -((double)(b->i)))))-((short)((((double)(b->i)) +((double)(b->i)))))-((short)((((int)((-4) + (42) *((long)((((int)((-4))) >>((int)((0xF32))))))+((long)((((double)((0xDC06))) *((double)(b->i)))))-((int)((((double)(b->i)) -((double)((3))))))+((long)((((double)(b->i)) *((double)((3)))))))) &((int)(b->i)))));
  return s.a.i;
}
int __attribute__((noinline,noclone))
test2 (void *q)
{
  struct S *b = &((struct R *)q)->a;
  s.a.i = (0x239EE) + (40) *((int)((((int)((4))) |((int)(s.a.i)))))-((long)((((double)(s.a.i)) +((double)((65536))))))+((long)((((int)(s.a.i)) &((int)((-1))))))+((short)((((int)(s.a.i)) %((int)((0)))))) + (0xBD9) -((int)((((double)(s.a.i)) *((double)(s.a.i)))))+((int)((((int)((0xE9) + (0xF7) *((int)((((int)((0x82AB9))) |((int)(s.a.i)))))-((long)((((double)(s.a.i)) +((double)((4194304))))))+((long)((((int)(s.a.i)) &((int)((0))))))+((short)((((int)(s.a.i)) %((int)((274877906944)))))))) <<((int)((8) + (-43) *((int)((((int)((9223372036854775808))) |((int)(s.a.i)))))-((long)((((double)(s.a.i)) +((double)((0xFA7))))))+((long)((((int)(s.a.i)) &((int)((0))))))+((short)((((int)(s.a.i)) %((int)((2)))))))))))-((int)((((int)((0xC) + (42) *((int)((((int)((0))) |((int)(s.a.i)))))-((long)((((double)(s.a.i)) +((double)((0))))))+((long)((((int)(s.a.i)) &((int)((0x7503))))))+((short)((((int)(s.a.i)) %((int)((0x3)))))))) <<((int)(s.a.i)))));
  b->i = (0x332) + (02) +((int)((((int)((3))) ^((int)(b->i))))) + (43) *((long)((((int)((0x18AFF) + (-43) +((int)((((int)((0xBFEE))) ^((int)(b->i))))))) &((int)(((int)((((int)((3))) ^((int)(b->i))))))))))+((long)((((double)((19))) +((double)((-4))))));
  return s.a.i;
}
int __attribute__((noinline,noclone))
test3 (void *q)
{
  s.a.i = (0x80B) + (42) *((long)((((int)(s.a.i)) >>((int)((-1))))))*((short)((((double)(s.a.i)) *((double)(s.a.i))))) + (42) -((long)((((int)(s.a.i)) &((int)(s.a.i)))))-((short)((((int)((-1) + (0x843C9) *((long)((((int)(s.a.i)) >>((int)((0))))))*((short)((((double)(s.a.i)) *((double)(s.a.i))))))) |((int)(s.a.i)))));
  ((struct S *)((char *)q + sizeof (int)))->i = (-4) + (0xDA) -((short)((((int)((35))) &((int)(((struct S *)((char *)q + sizeof (int)))->i)))))*((int)((((int)(((struct S *)((char *)q + sizeof (int)))->i)) <<((int)((3))))))-((int)((((int)(((struct S *)((char *)q + sizeof (int)))->i)) >>((int)(((struct S *)((char *)q + sizeof (int)))->i)))))*((long)((((int)(((struct S *)((char *)q + sizeof (int)))->i)) ^((int)((35))))))+((long)((((int)(((struct S *)((char *)q + sizeof (int)))->i)) ^((int)((3)))))) + (0x54A2B) *((long)((((int)((0x59A5) + (0xD8AE) -((short)((((int)((3))) &((int)(((struct S *)((char *)q + sizeof (int)))->i)))))*((int)((((int)(((struct S *)((char *)q + sizeof (int)))->i)) <<((int)((7))))))-((int)((((int)(((struct S *)((char *)q + sizeof (int)))->i)) >>((int)(((struct S *)((char *)q + sizeof (int)))->i)))))*((long)((((int)(((struct S *)((char *)q + sizeof (int)))->i)) ^((int)((0x7AC))))))+((long)((((int)(((struct S *)((char *)q + sizeof (int)))->i)) ^((int)((3)))))))) <<((int)(((struct S *)((char *)q + sizeof (int)))->i)))))-((long)((((int)(((struct S *)((char *)q + sizeof (int)))->i)) <<((int)((0x1873) + (-43) -((short)((((int)((3))) &((int)(((struct S *)((char *)q + sizeof (int)))->i)))))*((int)((((int)(((struct S *)((char *)q + sizeof (int)))->i)) <<((int)((35))))))-((int)((((int)(((struct S *)((char *)q + sizeof (int)))->i)) >>((int)(((struct S *)((char *)q + sizeof (int)))->i)))))*((long)((((int)(((struct S *)((char *)q + sizeof (int)))->i)) ^((int)((3))))))+((long)((((int)(((struct S *)((char *)q + sizeof (int)))->i)) ^((int)((-4)))))))))));
  return s.a.i;
}
extern void abort (void);
int
main()
{
  if ((0x6))
    { return (2048); }
  s.a.i = (-2) + (-43) +((long)((((int)((-2))) ^((int)((1))))))+((long)((((int)((-2))) |((int)(s.a.i)))))+((long)((((double)(s.a.i)) -((double)((-2))))))*((long)((((double)(s.a.i)) +((double)((1)))))) + (-43) *((long)((((int)(s.a.i)) >>((int)((3) + (-43) +((long)((((int)((17))) ^((int)((5))))))+((long)((((int)((-2))) |((int)(s.a.i)))))+((long)((((double)(s.a.i)) -((double)((0x9))))))*((long)((((double)(s.a.i)) +((double)((-2)))))))))))-((short)((((int)(s.a.i)) &((int)((-2) + (-43) +((long)((((int)((-2))) ^((int)((1))))))+((long)((((int)((1))) |((int)(s.a.i)))))+((long)((((double)(s.a.i)) -((double)((-2))))))*((long)((((double)(s.a.i)) +((double)((5)))))))))))-((short)((((int)(s.a.i)) <<((int)(s.a.i)))))*((int)((((double)(s.a.i)) -((double)(s.a.i)))))+((int)((((int)((0xB1) + (40) +((long)((((int)((9))) ^((int)((1))))))+((long)((((int)((17))) |((int)(s.a.i)))))+((long)((((double)(s.a.i)) -((double)((-2))))))*((long)((((double)(s.a.i)) +((double)((0x24D3)))))))) <<((int)((0xF11) + (0x6A7) +((long)((((int)((0xD2187))) ^((int)((-2))))))+((long)((((int)((1))) |((int)(s.a.i)))))+((long)((((double)(s.a.i)) -((double)((65))))))*((long)((((double)(s.a.i)) +((double)((1)))))))))));
  s.a.j = (2) + (42) -((int)((((double)(s.a.j)) *((double)((-3))))))+((long)((((int)((2))) &((int)(s.a.j)))))+((int)((((int)((6))) |((int)(s.a.j)))))-((long)((((double)(s.a.j)) +((double)((-3)))))) + (0x1A865A) +((long)((((int)((0) + (0xC5C86) -((int)((((double)(s.a.j)) *((double)((0xF59C))))))+((long)((((int)((-3))) &((int)(s.a.j)))))+((int)((((int)((0xEA))) |((int)(s.a.j)))))-((long)((((double)(s.a.j)) +((double)((0xCB2)))))))) |((int)((2) + (0xA4B19) -((int)((((double)(s.a.j)) *((double)((-3))))))+((long)((((int)((0xB979D))) &((int)(s.a.j)))))+((int)((((int)((34))) |((int)(s.a.j)))))-((long)((((double)(s.a.j)) +((double)((0x5B161)))))))))));
  if (((int)((int)test1 ((void *)&s) != (-4) + (43) *((int)((((double)((3))) *((double)((-4))))))) + (0x9E15) *((int)((((int)((int)test1 ((void *)&s))) ^((int)((0x3251B))))))*((long)((((int)((42))) %((int)((0x09C66))))))-((short)((((int)((0xA9))) %((int)((0x33F) *((int)((((double)((3))) *((double)((8)))))))))))-((long)((((int)((-43) *((int)((((double)((0xD772B))) *((double)((-4)))))))) ^((int)((int)test1 ((void *)&s))))))+((short)((((int)(((int)((((double)((-4))) *((double)((-4)))))))) ^((int)((19) + (58) *((int)((((double)((3))) *((double)((3)))))))))))+((int)((((int)((131))) |((int)((-43))))))*((short)((((int)((int)test1 ((void *)&s))) ^((int)((int)test1 ((void *)&s))))))*((int)((((int)((int)test1 ((void *)&s))) &((int)(((int)((((double)((0x041F3))) *((double)((7)))))))))))))
    { abort (); }
  s.a.i = (0x002C) + (12) +((int)((((int)((1))) |((int)(s.a.i)))))-((long)((((double)((65))) +((double)((0xD7))))))*((int)((((double)((-2))) +((double)(s.a.i)))))-((long)((((double)(s.a.i)) -((double)((-2)))))) + (106) +((short)((((int)(s.a.i)) >>((int)((65) + (-43) +((int)((((int)((0x23A1))) |((int)(s.a.i)))))-((long)((((double)((0xB515))) +((double)((9))))))*((int)((((double)((0))) +((double)(s.a.i)))))-((long)((((double)(s.a.i)) -((double)((17)))))))))))+((short)((((int)(s.a.i)) &((int)(s.a.i)))))-((int)((((int)((1) + (0xC701F) +((int)((((int)((3))) |((int)(s.a.i)))))-((long)((((double)((1))) +((double)((9))))))*((int)((((double)((1))) +((double)(s.a.i)))))-((long)((((double)(s.a.i)) -((double)((0xC28BB)))))))) >>((int)((129) + (170) +((int)((((int)((1))) |((int)(s.a.i)))))-((long)((((double)((1))) +((double)((0))))))*((int)((((double)((65))) +((double)(s.a.i)))))-((long)((((double)(s.a.i)) -((double)((9)))))))))))+((int)((((int)(s.a.i)) %((int)((0x130) + (0x55E) +((int)((((int)((-2))) |((int)(s.a.i)))))-((long)((((double)((0x065))) +((double)((-2))))))*((int)((((double)((0x02))) +((double)(s.a.i)))))-((long)((((double)(s.a.i)) -((double)((-2)))))))))))*((short)((((int)(s.a.i)) <<((int)((1) + (22) +((int)((((int)((129))) |((int)(s.a.i)))))-((long)((((double)((1))) +((double)((5))))))*((int)((((double)((-2))) +((double)(s.a.i)))))-((long)((((double)(s.a.i)) -((double)((1)))))))))));
  s.a.j = (-3) + (-43) +((int)((((int)((-3))) |((int)(s.a.j)))))*((int)((((double)(s.a.j)) -((double)(s.a.j)))))+((int)((((double)(s.a.j)) *((double)(s.a.j)))))+((long)((((double)(s.a.j)) -((double)(s.a.j))))) + (42) *((short)((((double)(s.a.j)) *((double)(s.a.j)))))*((int)((((int)(s.a.j)) %((int)((-3) + (42) +((int)((((int)((-3))) |((int)(s.a.j)))))*((int)((((double)(s.a.j)) -((double)(s.a.j)))))+((int)((((double)(s.a.j)) *((double)(s.a.j)))))+((long)((((double)(s.a.j)) -((double)(s.a.j))))))))))+((long)((((int)((66) + (0xAFFFCD) +((int)((((int)((130))) |((int)(s.a.j)))))*((int)((((double)(s.a.j)) -((double)(s.a.j)))))+((int)((((double)(s.a.j)) *((double)(s.a.j)))))+((long)((((double)(s.a.j)) -((double)(s.a.j))))))) ^((int)((34) + (42) +((int)((((int)((6))) |((int)(s.a.j)))))*((int)((((double)(s.a.j)) -((double)(s.a.j)))))+((int)((((double)(s.a.j)) *((double)(s.a.j)))))+((long)((((double)(s.a.j)) -((double)(s.a.j))))))))));
  if ((0xE09C))
    { abort (); }
  s.a.i = (9) + (42) +((long)((((int)((0xF42A))) &((int)((-2)))))) + (58) -((short)((((int)(s.a.i)) &((int)((-2) + (-43) +((long)((((int)((0x8))) &((int)((-2)))))))))))*((long)((((double)((-2) + (0x841) +((long)((((int)((1))) &((int)((-2)))))))) +((double)((-2) + (34) +((long)((((int)((129))) &((int)((65)))))))))))-((long)((((int)((0xF44) + (-43) +((long)((((int)((1))) &((int)((0)))))))) |((int)((3) + (43) +((long)((((int)((0x6BD))) &((int)((0xC67)))))))))));
  s.a.j = (-3) + (-43) *((int)((((double)(s.a.j)) *((double)((34))))))*((short)((((int)(s.a.j)) &((int)((0x01))))))-((short)((((double)(s.a.j)) *((double)(s.a.j)))))+((long)((((double)((-3))) *((double)(s.a.j))))) + (0xD0) -((int)((((int)((6) + (-43) *((int)((((double)(s.a.j)) *((double)((2))))))*((short)((((int)(s.a.j)) &((int)((-3))))))-((short)((((double)(s.a.j)) *((double)(s.a.j)))))+((long)((((double)((0x58))) *((double)(s.a.j))))))) <<((int)((-3) + (42) *((int)((((double)(s.a.j)) *((double)((6))))))*((short)((((int)(s.a.j)) &((int)((6))))))-((short)((((double)(s.a.j)) *((double)(s.a.j)))))+((long)((((double)((2))) *((double)(s.a.j))))))))));
  if (((int)((int)test3 ((void *)&s) != (0x4) + (42) +((long)((((int)((0x955))) >>((int)(test3 ((void *)&s))))))*((long)((((int)(test3 ((void *)&s))) %((int)((3))))))) + (-43) +((short)((((int)((-4) + (0x46FE) +((long)((((int)((35))) >>((int)(test3 ((void *)&s))))))*((long)((((int)(test3 ((void *)&s))) %((int)((1)))))))) <<((int)(((long)((((int)(test3 ((void *)&s))) %((int)((3)))))))))))*((long)((((int)(((long)((((int)((3))) >>((int)(test3 ((void *)&s))))))*((long)((((int)(test3 ((void *)&s))) %((int)((3)))))))) <<((int)(((long)((((int)((0x15356))) >>((int)(test3 ((void *)&s))))))*((long)((((int)(test3 ((void *)&s))) %((int)((0x7A02)))))))))))+((short)((((int)(((long)((((int)(test3 ((void *)&s))) %((int)((-4)))))))) <<((int)((int)test3 ((void *)&s))))))*((int)((((int)((int)test3 ((void *)&s))) >>((int)(((long)((((int)((2))) >>((int)(test3 ((void *)&s))))))*((long)((((int)(test3 ((void *)&s))) %((int)((7)))))))))))*((short)((((int)((int)test3 ((void *)&s))) <<((int)(((long)((((int)((0xB3))) >>((int)(test3 ((void *)&s)))))))))))))
    { abort (); }
  return (0);
}
/* ProgramSourceLLVM */
