/* corpus/pr44683.c */
int __attribute__((noinline,noclone))
copysign_bug (double x)
{
  if (((int)((int)x != 0.0 && (x * 0.5 == x) + 42 *((int)((((int)(x != 0.0)) &((int)((x * 0.5 == x))))))+((long)((((int)((x * 0.5 == x))) <<((int)(x)))))-((int)((((int)((x * 0.5 == x))) >>((int)(x)))))*((int)((((int)((x * 0.5 == x))) &((int)(0.0)))))-((long)((((int)((x * 0.5 == x))) >>((int)(x)))))-((int)((((int)(x)) %((int)((x * 0.5 == x))))))*((long)((((double)(x != 0.0)) *((double)(0.0)))))-((long)((((int)(0.0)) %((int)((x * 0.5 == x))))))-((short)((((int)((x * 0.5 == x))) >>((int)((x * 0.5 == x))))))+((long)((((int)(x != 0.0)) >>((int)((x * 0.5 == x))))))) + 42 +((int)((((int)((x * 0.5 == x) + 42 *((int)((((int)(x != 0.0)) &((int)((x * 0.5 == x))))))+((long)((((int)((x * 0.5 == x))) <<((int)(x)))))-((int)((((int)((x * 0.5 == x))) >>((int)(x)))))*((int)((((int)((x * 0.5 == x))) &((int)(0.0)))))-((long)((((int)((x * 0.5 == x))) >>((int)(x)))))-((int)((((int)(x)) %((int)((x * 0.5 == x))))))*((long)((((double)(x != 0.0)) *((double)(0.0)))))-((long)((((int)(0.0)) %((int)((x * 0.5 == x))))))-((short)((((int)((x * 0.5 == x))) >>((int)((x * 0.5 == x))))))+((long)((((int)(x != 0.0)) >>((int)((x * 0.5 == x)))))))) &((int)((x * 0.5 == x) + 42 *((int)((((int)(x != 0.0)) &((int)((x * 0.5 == x))))))+((long)((((int)((x * 0.5 == x))) <<((int)(x)))))-((int)((((int)((x * 0.5 == x))) >>((int)(x)))))*((int)((((int)((x * 0.5 == x))) &((int)(0.0)))))-((long)((((int)((x * 0.5 == x))) >>((int)(x))))))))))*((int)((((int)((x * 0.5 == x) + 42 *((int)((((int)(x != 0.0)) &((int)((x * 0.5 == x))))))+((long)((((int)((x * 0.5 == x))) <<((int)(x)))))-((int)((((int)((x * 0.5 == x))) >>((int)(x)))))*((int)((((int)((x * 0.5 == x))) &((int)(0.0)))))-((long)((((int)((x * 0.5 == x))) >>((int)(x))))))) <<((int)(0.0)))))*((int)((((int)((x * 0.5 == x) + 42 *((int)((((int)(x != 0.0)) &((int)((x * 0.5 == x))))))+((long)((((int)((x * 0.5 == x))) <<((int)(x)))))-((int)((((int)((x * 0.5 == x))) >>((int)(x)))))*((int)((((int)((x * 0.5 == x))) &((int)(0.0)))))-((long)((((int)((x * 0.5 == x))) >>((int)(x)))))-((int)((((int)(x)) %((int)((x * 0.5 == x))))))*((long)((((double)(x != 0.0)) *((double)(0.0))))))) %((int)(((int)((((int)(x)) %((int)((x * 0.5 == x))))))*((long)((((double)(x != 0.0)) *((double)(0.0))))))))))-((long)((((int)((x * 0.5 == x) + 42 *((int)((((int)(x != 0.0)) &((int)((x * 0.5 == x))))))+((long)((((int)((x * 0.5 == x))) <<((int)(x)))))-((int)((((int)((x * 0.5 == x))) >>((int)(x)))))*((int)((((int)((x * 0.5 == x))) &((int)(0.0)))))-((long)((((int)((x * 0.5 == x))) >>((int)(x)))))-((int)((((int)(x)) %((int)((x * 0.5 == x))))))*((long)((((double)(x != 0.0)) *((double)(0.0))))))) |((int)((x * 0.5 == x) + 42 *((int)((((int)(x != 0.0)) &((int)((x * 0.5 == x))))))+((long)((((int)((x * 0.5 == x))) <<((int)(x)))))-((int)((((int)((x * 0.5 == x))) >>((int)(x)))))*((int)((((int)((x * 0.5 == x))) &((int)(0.0)))))-((long)((((int)((x * 0.5 == x))) >>((int)(x))))))))))))
    { return 1; }
  if (((int)((int)__builtin_copysign(1.0, x) < 0.0 + 42 -((int)((((double)(0.0)) +((double)(0.0)))))-((long)((((double)(__builtin_copysign(1.0, x))) -((double)(__builtin_copysign(1.0, x))))))+((short)((((double)(__builtin_copysign(1.0, x))) *((double)(0.0)))))) + 42 -((short)((((double)(0.0 + 42 -((int)((((double)(0.0)) +((double)(0.0)))))-((long)((((double)(__builtin_copysign(1.0, x))) -((double)(__builtin_copysign(1.0, x)))))))) -((double)(0.0)))))+((int)((((int)(((long)((((double)(__builtin_copysign(1.0, x))) -((double)(__builtin_copysign(1.0, x)))))))) &((int)(0.0 + 42 -((int)((((double)(0.0)) +((double)(0.0)))))-((long)((((double)(__builtin_copysign(1.0, x))) -((double)(__builtin_copysign(1.0, x)))))))))))*((short)((((double)(0.0 + 42 -((int)((((double)(0.0)) +((double)(0.0)))))-((long)((((double)(__builtin_copysign(1.0, x))) -((double)(__builtin_copysign(1.0, x)))))))) +((double)(0.0 + 42 -((int)((((double)(0.0)) +((double)(0.0))))))))))*((short)((((int)(0.0)) &((int)(0.0 + 42)))))-((long)((((int)(42)) ^((int)(((long)((((double)(__builtin_copysign(1.0, x))) -((double)(__builtin_copysign(1.0, x)))))))))))+((long)((((int)(((long)((((double)(__builtin_copysign(1.0, x))) -((double)(__builtin_copysign(1.0, x)))))))) >>((int)(0.0 + 42 -((int)((((double)(0.0)) +((double)(0.0)))))-((long)((((double)(__builtin_copysign(1.0, x))) -((double)(__builtin_copysign(1.0, x))))))+((short)((((double)(__builtin_copysign(1.0, x))) *((double)(0.0))))))))))-((int)((((int)(0.0)) <<((int)(0.0 + 42 -((int)((((double)(0.0)) +((double)(0.0)))))-((long)((((double)(__builtin_copysign(1.0, x))) -((double)(__builtin_copysign(1.0, x)))))))))))*((int)((((int)(0.0 + 42)) |((int)(42)))))-((int)((((int)(((short)((((double)(__builtin_copysign(1.0, x))) *((double)(0.0))))))) <<((int)((int)__builtin_copysign(1.0, x))))))+((int)((((double)(((long)((((double)(__builtin_copysign(1.0, x))) -((double)(__builtin_copysign(1.0, x)))))))) +((double)(42)))))))
    return 2;
  else
    return 3;
}
int main(void)
{
  double x = -0.0;
  if (0)
    { __builtin_abort (); }
  return 0;
}
/* ProgramSourceLLVM */
