/* corpus/pr44683.c */
int __attribute__((noinline,noclone))
copysign_bug (double x)
{
  if (((int)((int)x != 0.0 && (x * 0.5 == x) + 42 -((long)((((int)(0.0)) |((int)(x != 0.0)))))-((long)((((int)((x * 0.5 == x))) <<((int)((x * 0.5 == x))))))+((long)((((double)(x != 0.0)) +((double)(0.0)))))*((long)((((int)(0.0)) |((int)(x)))))+((long)((((int)((x * 0.5 == x))) <<((int)(x)))))) + 42 *((long)((((double)((int)x != 0.0)) *((double)(((long)((((int)(0.0)) |((int)(x))))))))))+((long)((((int)((int)x)) &((int)((int)x != 0.0)))))+((short)((((int)((x * 0.5 == x) + 42 -((long)((((int)(0.0)) |((int)(x != 0.0)))))-((long)((((int)((x * 0.5 == x))) <<((int)((x * 0.5 == x)))))))) <<((int)((x * 0.5 == x) + 42)))))-((short)((((int)(0.0)) &((int)((int)x != 0.0)))))*((int)((((int)((x * 0.5 == x) + 42 -((long)((((int)(0.0)) |((int)(x != 0.0))))))) |((int)((x * 0.5 == x) + 42)))))+((long)((((int)((x * 0.5 == x) + 42)) &((int)(((long)((((int)((x * 0.5 == x))) <<((int)(x))))))))))*((int)((((int)(((long)((((double)(x != 0.0)) +((double)(0.0)))))*((long)((((int)(0.0)) |((int)(x))))))) >>((int)((int)x)))))+((long)((((int)(((long)((((double)(x != 0.0)) +((double)(0.0))))))) %((int)(((long)((((int)(0.0)) |((int)(x))))))))))+((long)((((int)((x * 0.5 == x) + 42 -((long)((((int)(0.0)) |((int)(x != 0.0)))))-((long)((((int)((x * 0.5 == x))) <<((int)((x * 0.5 == x))))))+((long)((((double)(x != 0.0)) +((double)(0.0)))))*((long)((((int)(0.0)) |((int)(x)))))+((long)((((int)((x * 0.5 == x))) <<((int)(x))))))) |((int)((x * 0.5 == x) + 42 -((long)((((int)(0.0)) |((int)(x != 0.0)))))-((long)((((int)((x * 0.5 == x))) <<((int)((x * 0.5 == x))))))+((long)((((double)(x != 0.0)) +((double)(0.0)))))*((long)((((int)(0.0)) |((int)(x)))))+((long)((((int)((x * 0.5 == x))) <<((int)(x))))))))))*((int)((((int)(((long)((((double)(x != 0.0)) +((double)(0.0)))))*((long)((((int)(0.0)) |((int)(x))))))) &((int)((int)x)))))))
    { return 1; }
  if (((int)((int)__builtin_copysign(1.0, x) < 0.0 + 42 -((int)((((int)(__builtin_copysign(1.0, x))) ^((int)(__builtin_copysign(1.0, x))))))*((short)((((double)(0.0)) *((double)(__builtin_copysign(1.0, x))))))*((long)((((int)(0.0)) <<((int)(0.0)))))*((short)((((double)(0.0)) *((double)(__builtin_copysign(1.0, x))))))-((long)((((double)(0.0)) +((double)(__builtin_copysign(1.0, x))))))+((int)((((int)(0.0)) ^((int)(0.0)))))*((short)((((double)(__builtin_copysign(1.0, x))) -((double)(0.0)))))+((int)((((int)(__builtin_copysign(1.0, x))) &((int)(0.0)))))) + 42 *((long)((((int)(0.0 + 42 -((int)((((int)(__builtin_copysign(1.0, x))) ^((int)(__builtin_copysign(1.0, x))))))*((short)((((double)(0.0)) *((double)(__builtin_copysign(1.0, x))))))*((long)((((int)(0.0)) <<((int)(0.0)))))*((short)((((double)(0.0)) *((double)(__builtin_copysign(1.0, x)))))))) ^((int)(0.0 + 42 -((int)((((int)(__builtin_copysign(1.0, x))) ^((int)(__builtin_copysign(1.0, x))))))*((short)((((double)(0.0)) *((double)(__builtin_copysign(1.0, x))))))*((long)((((int)(0.0)) <<((int)(0.0)))))*((short)((((double)(0.0)) *((double)(__builtin_copysign(1.0, x))))))-((long)((((double)(0.0)) +((double)(__builtin_copysign(1.0, x)))))))))))*((short)((((double)(0.0 + 42)) *((double)(42)))))-((short)((((double)(0.0 + 42)) *((double)(0.0)))))+((int)((((int)(((long)((((double)(0.0)) +((double)(__builtin_copysign(1.0, x)))))))) |((int)(((int)((((int)(__builtin_copysign(1.0, x))) ^((int)(__builtin_copysign(1.0, x))))))*((short)((((double)(0.0)) *((double)(__builtin_copysign(1.0, x))))))*((long)((((int)(0.0)) <<((int)(0.0)))))*((short)((((double)(0.0)) *((double)(__builtin_copysign(1.0, x)))))))))))+((short)((((int)(0.0)) |((int)(((int)((((int)(0.0)) ^((int)(0.0)))))*((short)((((double)(__builtin_copysign(1.0, x))) -((double)(0.0))))))))))*((int)((((int)(0.0)) ^((int)(((int)((((int)(__builtin_copysign(1.0, x))) ^((int)(__builtin_copysign(1.0, x))))))*((short)((((double)(0.0)) *((double)(__builtin_copysign(1.0, x))))))*((long)((((int)(0.0)) <<((int)(0.0)))))*((short)((((double)(0.0)) *((double)(__builtin_copysign(1.0, x)))))))))))-((short)((((int)(0.0)) ^((int)(0.0 + 42)))))*((short)((((int)(0.0 + 42 -((int)((((int)(__builtin_copysign(1.0, x))) ^((int)(__builtin_copysign(1.0, x))))))*((short)((((double)(0.0)) *((double)(__builtin_copysign(1.0, x))))))*((long)((((int)(0.0)) <<((int)(0.0)))))*((short)((((double)(0.0)) *((double)(__builtin_copysign(1.0, x))))))-((long)((((double)(0.0)) +((double)(__builtin_copysign(1.0, x)))))))) <<((int)((int)__builtin_copysign(1.0, x))))))+((long)((((int)(0.0 + 42 -((int)((((int)(__builtin_copysign(1.0, x))) ^((int)(__builtin_copysign(1.0, x))))))*((short)((((double)(0.0)) *((double)(__builtin_copysign(1.0, x))))))*((long)((((int)(0.0)) <<((int)(0.0)))))*((short)((((double)(0.0)) *((double)(__builtin_copysign(1.0, x)))))))) %((int)(0.0 + 42)))))))
    return 2;
  else
    return 3;
}
int main(void)
{
  double x = -0.0;
  if (0)
    { __builtin_abort (); }
  return 0;
}
/* ProgramSourceLLVM */
